services:
  image-processing:
    image: bozonx/image-processing-microservice
    container_name: image-processing-microservice
    hostname: image-processing-microservice
    restart: unless-stopped
    stop_grace_period: 30s
    user: '1000:1000'
    expose:
      - 8080
    ports:
      - '8080:8080'
    environment:
      - LOG_LEVEL=info
      - TZ=UTC
    healthcheck:
      test: [ "CMD", "node", "-e", "require('http').get('http://localhost:8080/api/v1/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
